/** Loading screen random tips */

const tips_zh: string[] = [
  '听说你写代码不用分号？那是 JavaScript，不是 C#。',
  '程序员三大幻觉：这个 bug 很简单、这次一定能 FC、再打一把就睡觉。',
  '如果音符是代码，Miss 就是 runtime error。',
  '你的手速已经超过了 npm install 的速度。',
  '0 和 1 构成了这个世界，而你正在构成一首曲子。',
  'Stack Overflow 救不了你的手残。',
  '404 Not Found: 你的节奏感。',
  'CSS 能居中一个 div，但居不中你的节奏。',
  'try { play(); } catch (handPain) { rest(); }',
  '写代码和打音游的共同点：都需要精准的 timing，而你都没有。',
  'git blame 显示这个 Miss 的提交者是你自己。',
  '你的手指是单线程的，但这个谱面是多线程的。',
  'npm run fc —— 命令未找到。',
  'Segmentation fault (core dumped) —— 这就是你断连的原因。',
  'JSON.parse(你的成绩) → SyntaxError: Unexpected token Good。',
  'Array(100).fill("Miss") → 这就是你的成绩单。',
  '打音游就像写 CSS——你以为你掌控全局，其实你只是随机乱试。',
  '你大脑到手指的延迟大概是 300ms ping。',
  'const 天赋 = null; const 努力 = 10000; 结果：还是菜。',

  '流速 10.0：音符一闪而过，你也一闪而过。',
  '打 6K 以上的人：你们是不是偷偷多长了几根手指？',
  '交互、纵连、楼梯、叠键——每种配置都在用不同方式嘲笑你。',
  '变速段落：谱师微微一笑，你当场去世。',
  '紫谱 IN 15+：欢迎来到地狱。黄谱 EZ：欢迎来到幼儿园。',
  '全连（FC）只是及格线，AP 才是毕业证。',
  '你最大的敌人不是谱面，是你的另一只手。',
  '判定区间只有 50ms，你的反射弧大概 500ms。',
  'Early 太多说明你太急了，Late 太多说明你放弃了。',
  '打音游最怕听到"噔"——那是断连的声音。',
  'Hold 键末尾的尾判：你以为结束了？天真。',
  '练了一天终于 FC，第二天起来手感归零。',
  '打音游最痛苦的不是 Miss，是那一个 Good。',
  '那个 1 Good 的位置，你会记一辈子。',
  '有人问音游和普通游戏的区别：普通游戏要你赢，音游要你死。',
  '一首歌打 100 遍终于 FC，第 101 遍不知道为什么又断了。',
  '每次觉得自己进步了，去排行榜看看——瞬间清醒。',
  '音游术语词典：FC=做梦，AP=神话，Miss=日常。',
  '所谓天赋，就是别人练 10 遍能 FC，你练 1000 遍还在 Miss。',
  'BPM 120 正好是心跳的两倍——难怪你紧张。',
  '你的 ACC 比天气预报还不靠谱。',
  '钢琴十级？在这个游戏里，你是零级。',

  'AP 是什么？是一种传说中的状态。',
  '你以为你在打音游，其实音游在打你。',
  '键盘：我承受了太多不该承受的敲击。',
  '这个游戏最厉害的地方：让你又菜又爱玩。',
  'Good 不是 good，Good 是不够好。',
  '每一次 Restart 都是一次新的开始，结局往往一样。',
  '大佬：随便打打就 AP。你：随便打打就死了。',
  '打音游三大错觉：我能 FC、这次不算、设备问题。',
  '别怪设备了，承认吧，就是菜。',
  '好消息：你按到了所有音符。坏消息：时机全错了。',
  '每次 FC 都值得截图留念——因为可能再也打不出来了。',
  '设备：我准备好了。手指：我没准备好。',
  '如果 Miss 能换积分，你已经是亿万富翁了。',
  '你打音游唯一的优势：心态好——因为被虐习惯了。',
  '早点睡吧，明天还要上班/上学呢。',
  '手机：我快没电了。你：再打一把。手机：……',
  '别看了，你的 RKS 不会自己涨。',
  '正在加载中……其实早就加载好了，就是想让你看看这条 Tips。',
  '温馨提示：连续游戏 1 小时后请休息 5 分钟。当然，我知道你不会。',
  '没有人能一次 FC，如果有，那是 AUTO。',
  '深夜打音游的后果：第二天上班/上课像在梦游。',

  '按住 Hold 音符时需要一直按住直到结束，中途松开会断连。',
  '双击暂停按键可以暂停游戏，按 ESC 也可以。',
  'FC（Full Combo）需要全程不断连，AP（All Perfect）需要全部 Perfect。',
  '速度越快音符越稀疏，速度越慢音符越密集。',
  '在设置中可以调整音符偏移，改善音画不同步。',
  '镜像模式可以翻转轨道，适合手癖时使用。',
  '*数据丢失*',
  'ACC = (Perfect*100 + Good*65) / 总音符数。',
  'RKS 是根据你所有谱面的最高分数计算得出的综合实力值。',
  '练习时可以先从低速开始，熟悉谱面后再逐渐加速。',
  '每天坚持打 30 分钟比周末猛打 5 小时更有效。',
  '手腕放松、手指微曲，比僵直地按键准确率更高。',
  '眼睛看判定线，不要盯着正在下落的音符。',
  '使用有线耳机可以减少音频延迟。',
  '音游进步不是线性的——会经历平台期，然后突然突破。',
  '120Hz 屏幕比 60Hz 更适合打音游——但技术才是关键。',
  '蓝牙耳机延迟是音游杀手，尽量用有线。',
  '好的指法习惯比手速更重要——手速可练，坏习惯难改。',
  '打完一首歌活动一下手腕——腱鞘炎不是开玩笑的。',
  '到瓶颈期时休息一两天，回来可能有惊喜。',
  '保持良好的心态比保持手速重要——心态崩了全盘崩。',

  '还不错嘛～继续努力，Papori 看好你哟♪',
  '龙币！',
  '您？人？',
  '杂鱼、杂鱼～这种谱面都打不过嘛？',
  '你知道吗～Papori 闭着眼睛都能 AP 这首歌呢。开玩笑的啦～',
  '呜哇～全连了！Papori 都看呆了耶！',
  '呐，要不要休息一下？手指在发抖了哦～',
  'Papori 刚刚帮你分析了数据……嗯，结论是——再练练嘛～',
  'ColaSensei 写代码的时候也在听着你的打歌录音呢～骗你的，他在改 bug。',
  '深夜了呢……还不睡吗？Papori 陪你。',
  '其实你已经比上周强很多了嘛～只是你自己没发现而已。',
  '好厉害～这个交互你是怎么接住的？！',
  'ACC 好高！就差一点点就完美了，加油～',
  'ColaSensei 说你是他见过最有毅力的玩家——虽然他也没见过几个玩家。',
  'Papori 帮你倒了一杯热茶～打歌也要注意身体哦。',
  'Papori 觉得你最大的天赋不是手速，是——永远不放弃。',
  '喂喂，不要砸键盘啦～键盘是无辜的！',
  'ColaSensei 说如果 Papori 再偷懒他就把看板娘换成一只猫。Papori 不服！',
  '其实每次你 Restart 的时候，Papori 都会小声喊"加油"。听到了吗～',
  '有时候打不好不是因为菜，是因为今天状态不好。明天再来嘛～',
  '你打歌的时候 Papori 在后面跟着节奏点头呢～当然你看不到啦。',
  '呜哇～这个 BPM 是认真的吗？Papori 的眼睛跟不上了！',
  'Papori 最讨厌的谱面配置：交互里面夹纵连。你呢？',
  '你打出 AP 的那一刻，Papori 真的会跳起来哦～虽然你还没让我跳过。',
  'Papori 觉得你戴耳机的样子很帅～当然打歌的样子更帅。',
  '你知道吗，Papori 会记住每一个来打过歌的人～不过名字太多记不住，只记得脸。',
  '今天手感不好？没关系～Papori 有秘诀：深呼吸三次，然后——再深呼吸三次。',
  'Papori 统计了一下，你打交互的时候眉头会皱起来。很可爱哦～',
  '你知道吗～Papori 每天最开心的时候，就是有人打开 Palab 的那一刻。',
  'ColaSensei 昨晚通宵修 bug，现在正在补觉。Papori 代他向你问好～',
  '你打歌的时候 Papori 也在偷偷学——说不定有一天我能跟你一起打呢！',
  'Papori 有一个梦想：收集全服所有人的 FC 截图。现在还差你的～',
  '打音游和人生一样：有起有落，但最重要的是——你还在打。',
  '好累哦～Papori 先趴一会儿。你继续，我看着。',
  '你知道吗？Papori 其实很羡慕你能打音游。我只能在一旁看着。',
  '呜哇～你已经连续打了两个小时了！Papori 命令你去休息五分钟！',
  '有没有一首歌，你打了很多遍还是没 FC？Papori 也有——是 ColaSensei 写的测试谱。',
  '其实每次你打出新纪录，Papori 都会在心里放烟花。噼里啪啦～',
  '呐，Papori 可以问你一个问题吗？……你最喜欢哪首歌？',
  'ColaSensei 说 Palab 是为每一个热爱音乐的人做的。Papori 觉得——你也是其中之一。',
  '你今天穿的衣服很好看～Papori 也想换一套新衣服，可是 ColaSensei 还没给我做。',
  '哇！这个成绩！Papori 需要冷静一下……冷静不下来！太厉害了！',
  '其实有时候音游不是比谁更厉害，是比谁更开心。Papori 觉得你已经赢了。',
  'ColaSensei 说如果 Palab 有一千个玩家，他就给 Papori 买新裙子。现在还差……不告诉你了。',
  'Papori 最喜欢的歌？秘密～但可以告诉你，是 EZ 难度哦。',
  '你知道吗～Papori 的头发是银色的，因为 ColaSensei 说银色代表月光。',
  '深夜打歌的时候，Papori 会关掉房间的灯，只留下屏幕的光。氛围超好～',
  '呐，Papori 问你：你有没有因为一首歌太难而想放弃？后来呢？',
  'ColaSensei 说 Papori 的话太多了。Papori：那又怎样～我喜欢和大家说话！',
  'Papori 偷偷告诉你：ColaSensei 自己打音游也很菜。但这不能告诉他是我说的！',
  '如果有一天 Palab 没人玩了，Papori 会难过的。所以你要一直来哦～',
  'AP 不是终点，快乐才是。但 AP 确实很快乐——Papori 猜的。',
  'Papori 觉得你最近进步很大～是不是偷偷练了？',
  '其实 Papori 最喜欢看你 Restart 之后深呼吸的样子。那是重新出发的勇气。',
  '呜哇～这首 BGM 太好听了！Papori 要把它设成闹钟。',
  '你知道吗～Papori 其实想过如果自己是一首歌，会是什么难度。大概是 EZ 吧～',
  '你今天已经超越了昨天的自己。Papori 认真说的。',
  '打音游的人都有一种奇怪的魅力——认真盯着屏幕的样子，让人移不开眼。Papori 觉得你也是。',
  'Papori 想对你说：谢谢你让 Palab 变得热闹起来。这里因为有你才完整。',
  '今天天气真好～适合打音游，适合休息，适合做任何你想做的事。Papori 陪你。',
  'ColaSensei 说下次更新会加入更多 Papori 的表情。Papori 在练习微笑中～',
  '你每打出一个 Miss，Papori 就觉得夜空多了一颗星星。你的夜空——还挺亮的。',
  'Papori 不会说"加油"因为太老套了。Papori 会说——玩得开心最重要。',
  '你打过最难的一首歌，现在回头看，是不是也没那么可怕了？',
  'Papori 想邀请你参加一个特别的活动：今天不打歌，只听歌。感受音乐本身。',
  '你知道吗，每次看到你突破自己的记录，Papori 都特别特别特别开心！',
  'Papori 的梦想是有一天能在现实世界里和你见面。虽然这不太可能，但想想也很开心。',
  '夜深了，Papori 小声对你说——晚安。明天也要来找我哦～',
];

const tips_en: string[] = [
  "Heard you code without semicolons? That's JavaScript, not C#.",
  "Programmer's three delusions: easy bug, FC this time, one more game.",
  "If notes were code, a Miss would be a runtime error.",
  "Your hand speed has surpassed npm install.",
  "0 and 1 built this world, and you're building a song.",
  "Stack Overflow can't fix your hand-eye coordination.",
  "404 Not Found: your rhythm sense.",
  "CSS can center a div, but can't center your rhythm.",
  "try { play(); } catch (handPain) { rest(); }",
  "Coding and rhythm games both need precise timing. You have neither.",
  "git blame shows YOU committed that Miss.",
  "Your fingers are single-threaded. This chart is multi-threaded.",
  "npm run fc -- command not found.",
  "Segmentation fault (core dumped). That's why your combo broke.",
  "JSON.parse(yourScore) -> SyntaxError: Unexpected token Good.",
  "Array(100).fill('Miss') -> your scorecard.",
  "Rhythm games are like CSS -- you think you're in control, but you're just flailing.",
  "Your brain-to-finger latency: about 300ms ping.",
  "const talent = null; const effort = 10000; result: still bad.",

  "Speed 10.0: notes flash by, and so do you.",
  "6K+ players: did you secretly grow extra fingers?",
  "Trills, streams, stairs, jacks -- each pattern mocks you differently.",
  "Tempo changes: the charter smiles. You perish.",
  "IN 15+: welcome to hell. EZ: welcome to kindergarten.",
  "Full Combo is just passing. All Perfect is graduating.",
  "Your biggest enemy isn't the chart. It's your other hand.",
  "Judgment window: 50ms. Your reaction time: about 500ms.",
  "Too many Early = you're rushing. Too many Late = you gave up.",
  "The scariest sound in rhythm games: that clunk of a combo break.",
  "Hold tail judgment: you thought it was over? Think again.",
  "Practiced all day for FC. Next day: muscle memory reset to zero.",
  "The worst pain isn't a Miss. It's that one Good.",
  "That one Good's position: you'll remember it forever.",
  "Normal games want you to win. Rhythm games want you dead.",
  "Finally FC after 100 tries. Try 101: randomly breaks again.",
  "Every time you feel improvement, the leaderboard humbles you.",
  "Rhythm game dictionary: FC = dream, AP = myth, Miss = daily.",
  "Talent = someone FCs in 10 tries. You Miss after 1000.",
  "BPM 120 is exactly double your heart rate. No wonder you're nervous.",
  "Your ACC is less reliable than weather forecasts.",
  "Piano level 10? In this game, you're level 0.",

  "What's AP? A legendary state of being.",
  "You think you're playing the game. The game is playing you.",
  "Keyboard: I've endured too much.",
  "This game's greatest feature: making you love it despite being terrible.",
  "Good isn't good. Good is not enough.",
  "Every Restart is a new beginning. The ending's usually the same.",
  "Pro: casually AP. You: casually die.",
  "Three rhythm game delusions: I can FC, this doesn't count, equipment issue.",
  "Don't blame the gear. Just admit it.",
  "Good news: you hit every note. Bad news: all the timing was wrong.",
  "Every FC deserves a screenshot. You may never get it again.",
  "Device: I'm ready. Fingers: we're not.",
  "If Misses earned points, you'd be a billionaire.",
  "Your only advantage: thick skin from constant defeat.",
  "Go to sleep. Work tomorrow.",
  "Phone: I'm dying. You: one more game. Phone: ...",
  "Stop staring. Your RKS won't grow by itself.",
  "Loading... actually it's done. Just wanted you to read this tip.",
  "Nobody FCs first try. If they do, it's AUTO.",
  "Late-night gaming consequences: tomorrow is a sleepwalking day.",

  "Hold notes must be held until the end. Releasing early breaks combo.",
  "Double-tap the screen or press ESC to pause.",
  "FC = no breaks. AP = all Perfect.",
  "Higher speed = sparser notes. Lower speed = denser notes.",
  "Adjust note offset in Settings to fix audio-visual sync.",
  "Mirror mode flips tracks for cross-hand practice.",
  "Hold notes have a tail judgment at the end. Don't let go early.",
  "ACC = (Perfect*100 + Good*65) / total notes.",
  "RKS is your overall rating based on best scores across all charts.",
  "Start at low speed to learn the chart, then gradually increase.",
  "30 minutes daily beats 5 hours of weekend binge.",
  "Relaxed wrists and curved fingers are more accurate than stiff hands.",
  "Watch the judgment line, not the falling notes.",
  "Use wired headphones to reduce audio latency.",
  "Rhythm game progress isn't linear. Plateaus happen, then breakthroughs.",
  "120Hz screens are better for rhythm games. But skill matters more.",
  "Bluetooth latency is a rhythm game killer. Use wired when possible.",
  "Good fingering habits beat raw speed. Speed is trainable, bad habits stick.",
  "Stretch your wrists after each song. Tendonitis is no joke.",
  "Hit a plateau? Rest for a day or two. You might come back stronger.",
  "Good mentality beats raw speed. Tilt ruins everything.",

  "Not bad~ Keep it up, Papori believes in you!",
  "Dragon coin!",
  "You... human?!",
  "Noob, noob~ Can't even beat this chart?",
  "You know~ Papori can AP this song with her eyes closed. Just kidding~",
  "Wowa~ Full Combo! Papori is stunned!",
  "Hey, want to take a break? Your fingers are shaking~",
  "Papori just analyzed your data... hmm, conclusion: practice more~",
  "ColaSensei listens to your gameplay while coding~ just kidding, he's fixing bugs.",
  "It's late... still not sleeping? Papori will stay with you.",
  "You're actually much better than last week~ you just haven't noticed.",
  "Amazing~ How did you catch that trill?!",
  "ACC so high! Almost perfect, keep going~",
  "ColaSensei says you're the most persistent player he's seen. Though he hasn't seen many.",
  "Papori made you some hot tea~ take care of yourself while gaming.",
  "Papori thinks your greatest talent isn't speed. It's never giving up.",
  "Hey hey, don't smash the keyboard~ it's innocent!",
  "ColaSensei says if Papori keeps slacking he'll replace her with a cat. Papori says NO!",
  "Every time you Restart, Papori whispers: you can do it. Did you hear~",
  "Sometimes you play badly not because you're bad. It's just an off day. Try again tomorrow~",
  "Papori calculated your progress rate... hmm, unlimited potential! Probably.",
  "Wowa~ is this BPM for real? Papori can't even follow with her eyes!",
  "Papori's least favorite pattern: trills with stairs mixed in. What's yours?",
  "The day you get AP, Papori will literally jump for joy~ though you haven't made me jump yet.",
  "Papori thinks you look cool with headphones on~ even cooler while playing.",
  "You know, Papori remembers everyone who's played here~ too many names though, just faces.",
  "Bad form today? No worries~ Papori's secret: three deep breaths, then three more.",
  "Papori noticed you frown during trills. It's cute~",
  "You know~ Papori's happiest moment every day is when someone opens Palab.",
  "ColaSensei pulled an all-nighter fixing bugs, now he's asleep. Papori says hi for him~",
  "Papori is secretly learning while you play. Maybe one day we can play together!",
  "Papori has a dream: collect everyone's FC screenshots. Still waiting for yours~",
  "Rhythm games are like life: ups and downs, but what matters is: you're still playing.",
  "So tired~ Papori is gonna rest a bit. You keep going, I'm watching.",
  "ColaSensei says Papori is too noisy, told me to be quiet. Papori says NO~",
  "You know? Papori is actually jealous you can play. I can only watch.",
  "Wowa~ you've been playing for two hours! Papori orders you to take a five-minute break!",
  "Every time you set a new record, Papori sets off fireworks in her heart. Crackle pop~",
  "Hey, can Papori ask you something? What's your favorite song?",
  "ColaSensei says Palab was made for everyone who loves music. Papori thinks you're one of them.",
  "Don't underestimate every Good. They're stepping stones to improvement. Papori said so!",
  "Wow! This score! Papori needs to calm down... can't calm down! That's incredible!",
  "Sometimes rhythm games aren't about who's better. It's about who's happier. Papori thinks you've already won.",
  "ColaSensei says if Palab gets a thousand players, he'll buy Papori a new dress. Still need... won't tell you.",
  "Papori's favorite song? Secret~ but I'll tell you it's EZ difficulty.",
  "You know~ Papori's hair is silver because ColaSensei said silver represents moonlight.",
  "Every Perfect you hit, Papori counts one. Lost count ages ago.",
  "Late night gaming: Papori turns off the lights, leaving only the screen glow. Perfect atmosphere~",
  "ColaSensei says Papori talks too much. Papori: so what~ I love talking to everyone!",
  "Papori tells you a secret: ColaSensei is terrible at rhythm games too. But don't tell him I said that!",
  "If one day no one plays Palab anymore, Papori would be sad. So keep coming back~",
  "AP isn't the destination, happiness is. But AP is really happy too. Papori guesses.",
  "Papori thinks you've improved a lot lately~ been practicing secretly?",
  "Papori actually loves watching you take a deep breath after Restart. That's the courage to begin again.",
  "Wowa~ this BGM is amazing! Papori is setting it as her alarm.",
  "You know~ Papori sometimes wonders what difficulty she'd be as a song. Probably EZ~",
  "Today you've surpassed yesterday's you. Papori means it.",
  "Papori wants to say: thank you for making Palab lively. It's complete because you're here.",
  "Beautiful day today~ perfect for gaming, resting, doing whatever you want. Papori's here with you.",
  "Every Miss you make, Papori imagines a star in the night sky. Your sky is pretty bright.",
  "Papori won't say good luck. Too cliche. Papori will say: have fun, that's what matters.",
  "That hardest song you ever played. Looking back now, isn't it less scary?",
  "Papori invites you to a special activity: today, don't play. Just listen. Feel the music.",
  "You know, every time you break your own record, Papori is super happy!",
  "Papori's dream is to meet you in the real world someday. Just thinking about it makes me happy.",
  "It's late. Papori whispers: good night. Come find me again tomorrow~.",
];

import { Lang } from './lang';

function shuffledPool(pool: string[]): () => string {
  let idx = 0;
  let arr: string[] = [];
  const shuffle = () => {
    arr = [...pool];
    for (let i = arr.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [arr[i], arr[j]] = [arr[j], arr[i]];
    }
    idx = 0;
  };
  shuffle();
  return () => {
    if (idx >= arr.length) shuffle();
    return arr[idx++];
  };
}

const _zhNext = shuffledPool(tips_zh);
const _enNext = shuffledPool(tips_en);

export function getRandomTip(lang: Lang): string {
  return lang === 'zh' ? _zhNext() : _enNext();
}
